### PR TITLE
Bug/151 mime type

### PR DESCRIPTION
**Pull request by hahnd**
This fixes the issue where a browser will download the index.html to a file rather than rendering it as a web page.  I left the work around in the documentation just in case anyone encounters the problem.

- [ ] Do these changes modify the system output in any way? **[Yes or No]**</br>
If **yes**, please describe:</br>

## Pull Request Testing ##

- [ ] Describe testing already performed for these changes:</br>

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

- [ ] Do these changes include sufficient documentation updates, ensuring that no errors or warnings exist in the build of the documentation? **[Yes or No]**

- [ ] Do these changes include sufficient testing updates? **[Yes or No]**

- [ ] Will this PR result in changes to the test suite? **[Yes or No]**</br>
If **yes**, describe the new output and/or changes to the existing output:</br>

- [ ] Please complete this pull request review by **[Fill in date]**.</br>

## Pull Request Checklist ##
- [ ] Review the source issue metadata (labels, project, and milestone).
- [ ] Complete the PR definition above.
- [ ] Ensure the PR title matches the feature or bugfix branch name.
- [ ] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)**
Select: **Project**
Select: **Milestone** as the version that will include these changes
Select: **Development** to link to the original development issue.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue and delete your feature or bugfix branch from GitHub.

### CODE REVIEW

**Comment by hahnd** [comment]
Closes #151

**Comment by fossell** [comment]
@hahnd - I assume this PR requires testing the install on a separate account (e.g. METplus AWS account) like @JohnHalleyGotway was doing? If yes, @JohnHalleyGotway can you let me know if this is something you have time to do? If not, perhaps we could have @georgemccabe test the install on the METplus account to get familiar and see if he encounters any issue?

**Comment by hahnd** [comment]
Yes, this is part of the install process.

**Review by JohnHalleyGotway — CHANGES_REQUESTED** [review]
Thanks for cleaning up the installation instructions that were littered with typos!

I tested this via the METplus AWS account by [uninstalling](https://wrfcloud.readthedocs.io/en/latest/Users_Guide/installation.html#procedures-to-uninstall) and [re-installing](https://wrfcloud.readthedocs.io/en/latest/Users_Guide/installation.html#procedures-to-install) WRFCloud.

However, I ran into unexpected behavior when I was prompted with a new interactive question:
```
Uploading public SSH key to AWS...
Uploading build artifacts to S3 bucket (wrfcloud-9afee59a) ...
Uploading lambda_layer.zip to s3://wrfcloud-9afee59a/artifacts/lambda_layer.zip ...
Uploading lambda_function.zip to s3://wrfcloud-9afee59a/artifacts/lambda_function.zip ...
Enter the location of the Angular web application build: 
```
And it was waiting for user input.

Is this a new question that needs to be documented in the installation instructions? Or something that needs to be fixed for this PR?

**Comment by hahnd** [comment]
That is not a new question, but only asked if it cannot find the files.  Do other error messages indicate that the Angular web application build failed for some reason?

**Comment by JohnHalleyGotway** [comment]
@hahnd I no longer have the cloudshell window up to scan for logs, and the build files in /tmp have already aged off. Where should I be looking in the AWS management console to find this type of logging?

**Comment by hahnd** [comment]
Only in the CloudShell window.  If that’s gone, then they’re gone.

**Review by JohnHalleyGotway — COMMENTED** [review]
As we discussed via email, the underlying problem with my initial test was that the home directory of the CloudShell user was full. The hidden `.cache`, `.nvm`, and `.npm` directories were rather full:
```
207M    .cache
267M    .npm
410M    .nvm
```
Via CloudShell, I emptied all this out using the **Actions > Delete AWS CloudShell home directory** option.

I did notice that this installation question did reappear:
```
Would you like to enable autocompletion? This will set up your terminal so pressing TAB while typing Angular CLI commands will show possible options and autocomplete arguments. (Enabling autocompletion will modify configuration files in your home directory.) 
Yes
```
Perhaps it had gone away because the answer had been cached? And perhaps cleaning the cache prompted it again?

After cleaning and re-installing, the installation worked as expected. And most importantly, I was able to navigate to `app.metpluscloud.org` without the odd download behavior we'd previously dealt with.

So this PR fixes that behavior.

**Review by JohnHalleyGotway — APPROVED** [review]
I approve of these changes. Note that I did add a note to the installation instructions that the "autocompletion" question may appear.

**Comment by JohnHalleyGotway** [comment]
As decided on 2/27/23, @JohnHalleyGotway should update the installation instructions about required space for installation in the /home directory.

**Review by fossell — APPROVED** [review]
@JohnHalleyGotway - The updates to the documentation for Step 4 and cloud shell space requirements look good. Merging now.

**Pull request merged**
