### PR TITLE
A number of QOL improvements in preparation for real and WRF tasks

### PR DESCRIPTION
**Pull request by mkavulich**
This PR introduces a number of QOL improvements in error checking, runtime control, and test.yaml defaults

 - Updates to test.yaml
   - Change default values to be more reasonable for AWS cluster testing
   - Add new option "exists" that can specify different options for dealing with existing working directories for each task
     - "die" (default): previous behavior, script will die with an exception
     - "skip": skip the task for which there is an existing working directory
     - "remove": remove the working directory and create a fresh one
   - Allow local_data to be fully removed rather than needing to specify it as an empty string to pull remote data
 - Automatically create top-level workdir (this was previous behavior, got changed accidentally)
 - Save full config dictionary to runinfo; this is useful for debugging
 - Remove some bad lines and fix misleading messages
 - Populate and use stub "symlink" function that has behavior of os.symlink, except returns an exception if target does not exist
 - Raise exception in ungrib if no input files are found

## Expected Differences ##

- [ ] Do these changes modify the system output in any way? **No**

## Pull Request Testing ##

- [ ] Describe testing already performed for these changes:</br>

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>
  - Instructions for testing on Cheyenne will be provided in comment

- [ ] Do these changes include sufficient documentation updates, ensuring that no errors or warnings exist in the build of the documentation? **[No]**

- [ ] Do these changes include sufficient testing updates? **[No]**

- [ ] Will this PR result in changes to the test suite? **[No]**</br>

- [ ] Please complete this pull request review by **[2022-09-22]**.</br>

## Pull Request Checklist ##
- [ ] Review the source issue metadata (labels, project, and milestone).
- [ ] Complete the PR definition above.
- [ ] Ensure the PR title matches the feature or bugfix branch name.
- [ ] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)**
Select: **Project**
Select: **Milestone** as the version that will include these changes
Select: **Development** to link to the original development issue.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue and delete your feature or bugfix branch from GitHub.

### CODE REVIEW

**Comment by mkavulich** [comment]
# Testing details:

# Setup
### Clone and set up code on Cheyenne

```
git clone git@github.com:NCAR/wrfcloud -b feature/QOL_improvements
module load conda
conda activate /glade/p/ral/jntp/CCproject/wrfcloud/conda/wrfcloud
export PYTHONPATH=`pwd`/wrfcloud/python/src
cd wrfcloud/python/src/wrfcloud/runtime/
cp /glade/p/ral/jntp/CCproject/wrfcloud/wpsprd/geo_em.d01.nc configurations/test/
```

### Modify test.yml for Cheyenne values

```
    wpscodedir: /glade/p/ral/jntp/CCproject/wrfcloud/WPSV4.4_intel_serial_large-file/
    wrfcodedir: /glade/p/ral/jntp/CCproject/wrfcloud/WRFV4.4_intel_dmpar/
...
    workdir: /glade/scratch/your_name_here
...
    local_data: /glade/p/ral/jntp/CCproject/wrfcloud/input_data/gfs/2022060100/gfs.t00z.pgrb2.0p25.f*
```
### Run the test case, should be successful through metgrid
```
./run.py
{"time": "2022-09-16 15:45:23.000 +0000", "message": "Initializing production environment", "appName": "no_name", "className": "NoClass", "level": "INFO "}
{"time": "2022-09-16 15:45:23.000 +0000", "message": "Starting new run \"test\"", "appName": "wrfcloud-production", "className": "NoClass", "level": "INFO "}
...
...
2022-09-16 15:49:10.000 +0000 - INFO  - wrfcloud-test - Wrf - Setting up WRF for "test"
2022-09-16 15:49:10.000 +0000 - WARN  - wrfcloud-test - Wrf - wrfcloud.runtime.wrf is not fully implemented yet!
2022-09-16 15:49:10.000 +0000 - INFO  - wrfcloud-test - PostProc - Setting up post-processing for "test"
2022-09-16 15:49:10.000 +0000 - WARN  - wrfcloud-test - PostProc - wrfcloud.runtime.postproc isn't fully implemented yet!
```
## Test 1
Run the test case again, should fail due to existing workdir
```
./run.py
{"time": "2022-09-16 15:50:48.000 +0000", "message": "Initializing production environment", "appName": "no_name", "className": "NoClass", "level": "INFO "}
{"time": "2022-09-16 15:50:48.000 +0000", "message": "Starting new run \"test\"", "appName": "wrfcloud-production", "className": "NoClass", "level": "INFO "}
{"time": "2022-09-16 15:50:48.000 +0000", "message": "Could not read config file run.yml, trying test.yml", "appName": "wrfcloud-production", "className": "RunInfo", "level": "WARN "}
{"time": "2022-09-16 15:50:48.000 +0000", "message": "Setting up working directory /glade/scratch/kavulich/wrfcloud_PR_67_test", "appName": "wrfcloud-production", "className": "NoClass", "level": "INFO "}
{"time": "2022-09-16 15:50:48.000 +0000", "message": "Initializing test environment", "appName": "wrfcloud-production", "className": "NoClass", "level": "INFO "}
2022-09-16 15:50:48.000 +0000 - INFO  - wrfcloud-test - Ungrib - Setting up ungrib for "test"
2022-09-16 15:50:48.000 +0000 - FATAL - wrfcloud-test - NoClass - Directory already exists: 
                 /glade/scratch/kavulich/wrfcloud_PR_67_test/ungrib
                 Move or remove this directory before continuing.
Traceback (most recent call last):
  File "/glade/scratch/kavulich/wrfcloud/PR_67/wrfcloud/python/src/wrfcloud/runtime/./run.py", line 73, in <module>
    main()
  File "/glade/scratch/kavulich/wrfcloud/PR_67/wrfcloud/python/src/wrfcloud/runtime/./run.py", line 48, in main
    ungrib.start()
  File "/glade/scratch/kavulich/wrfcloud/PR_67/wrfcloud/python/src/wrfcloud/runtime/__init__.py", line 89, in start
    self.success = self.run()
  File "/glade/scratch/kavulich/wrfcloud/PR_67/wrfcloud/python/src/wrfcloud/runtime/ungrib.py", line 87, in run
    action = check_wd_exist(self.runinfo.exists,self.runinfo.ungribdir)
  File "/glade/scratch/kavulich/wrfcloud/PR_67/wrfcloud/python/src/wrfcloud/runtime/tools/check_wd_exist.py", line 33, in check_wd_exist
    raise FileExistsError(msg1 + msg2)
FileExistsError: Directory already exists: 
                 /glade/scratch/kavulich/wrfcloud_PR_67_test/ungrib
                 Move or remove this directory before continuing.
```
## Test 2
Modify test.yml to set `exists: remove` and re-run `./run.py`. You should now observe that the existing working directories are automatically removed and the tasks re-run.
```
vi test.yml
./run.py
...
...
2022-09-16 15:54:36.000 +0000 - INFO  - wrfcloud-test - Ungrib - Setting up ungrib for "test"
2022-09-16 15:54:36.000 +0000 - WARN  - wrfcloud-test - NoClass - Directory already exists: 
                 /glade/scratch/kavulich/wrfcloud_PR_67_test/ungrib
                 Config option set to remove existing directory.
2022-09-16 15:54:36.000 +0000 - DEBUG - wrfcloud-test - Ungrib - Creating WPS namelist
...
...
2022-09-16 15:56:35.000 +0000 - INFO  - wrfcloud-test - MetGrid - Setting up metgrid for "test"
2022-09-16 15:56:35.000 +0000 - WARN  - wrfcloud-test - NoClass - Directory already exists: 
                 /glade/scratch/kavulich/wrfcloud_PR_67_test/metgrid
                 Config option set to remove existing directory.
2022-09-16 15:56:35.000 +0000 - DEBUG - wrfcloud-test - MetGrid - Creating WPS namelist
...
```
## Test 3
Edit test.yml to set `exists: skip`, manually remove metgrid directory, and re-run `./run.py`. You should observe that the ungrib task is skipped and the old workdir used for the next step (metgrid).
```
vi test.yml
rm -rf /glade/scratch/your_name_here/metgrid
./run.py
...
...
2022-09-16 16:01:06.000 +0000 - INFO  - wrfcloud-test - Ungrib - Setting up ungrib for "test"
2022-09-16 16:01:06.000 +0000 - WARN  - wrfcloud-test - NoClass - Directory already exists: 
                 /glade/scratch/kavulich/wrfcloud_PR_67_test/ungrib
                 Config option set to skip task, returning to main program.
2022-09-16 16:01:06.000 +0000 - INFO  - wrfcloud-test - MetGrid - Setting up metgrid for "test"
...
...
```
## Test 4
Now edit test.yml to set `exists: remove` and modify the value of `local_data` to some junk value that does not correspond to input files (like removing the wildcard `*`), and re-run `./run.py`. You should observe that the run fails gracefully with the message that no input data was found, whereas the current version of develop would run through all the tasks with no error message.
```
vi test.yml
./run.py
...
...
2022-09-16 16:10:30.000 +0000 - ERROR - wrfcloud-test - Ungrib - List of input files is empty; check configuration
Traceback (most recent call last):
  File "/glade/scratch/kavulich/wrfcloud/PR_67/wrfcloud/python/src/wrfcloud/runtime/./run.py", line 73, in <module>
    main()
  File "/glade/scratch/kavulich/wrfcloud/PR_67/wrfcloud/python/src/wrfcloud/runtime/./run.py", line 48, in main
    ungrib.start()
  File "/glade/scratch/kavulich/wrfcloud/PR_67/wrfcloud/python/src/wrfcloud/runtime/__init__.py", line 89, in start
    self.success = self.run()
  File "/glade/scratch/kavulich/wrfcloud/PR_67/wrfcloud/python/src/wrfcloud/runtime/ungrib.py", line 98, in run
    self.get_files()
  File "/glade/scratch/kavulich/wrfcloud/PR_67/wrfcloud/python/src/wrfcloud/runtime/ungrib.py", line 56, in get_files
    raise FileNotFoundError('No input files found')
FileNotFoundError: No input files found
```
## Test 5
Now edit test.yml to delete or comment the local_data line, and re-run `./run.py`. You should observe a successful run that retrieves remote data, whereas the current version of develop would fail to read the local_data variable.
```
vi test.yml
./run.py
...
...
2022-09-16 16:11:21.000 +0000 - DEBUG - wrfcloud-test - Ungrib - Getting ungrib input files
2022-09-16 16:11:21.000 +0000 - DEBUG - wrfcloud-test - Ungrib - "local_data" not set; getting GRIB file(s) from remote source
2022-09-16 16:11:21.000 +0000 - DEBUG - wrfcloud-test - NoClass - Getting GRIB file(s) from external source (NOMADS or AWS S3)
2022-09-16 16:11:22.000 +0000 - DEBUG - wrfcloud-test - NoClass - NOMADS URL does not exist for forecast hour 0, trying AWS S3.
2022-09-16 16:11:30.000 +0000 - DEBUG - wrfcloud-test - NoClass - Pulled forecast hour 0 from AWS S3.
...
```

**Review by fossell — COMMENTED** [review]
I ran all the tests successfully. Please see the second issue I listed here at the bottom of these comments and let me know your thoughts on having the code dirs in test.yml instead of resources/ens_vars.yaml. I'm not super familiar with the latter, so might need David's insight on the best practice. Just want to make sure we're not overlooking something before approving. I'm ok with addressing that aspect later too and getting this PR in first if need be. 

I will note that I've been doing testing using a run.yml file now. And when that exists then the run doesn't use test.yml. It's not a huge deal, just a gotcha when they both exist and I forget and follow directions to edit the test.yml and nothing changes. Doh! 

Setup - success
Test 1 - success
Test 2 - success
Test 3 - success
Test 4 - success (Definitely needed error handling in here, good catch)
Test 5 - success (This is nice to not have to have empty string to force external data pull, since that will be the main way this system operates)
Test 6 - I also changed the working_dir to be something that doesn't exist, e.g. /glade/scratch/fossell/output (because /glade/scratch/your_name always exists) and this was an issue before that the directory had to exist, but this PR reimplements that lost feature. The test was successful and creates the new output directory. 

This PR addresses a couple existing issues:
1. Adding symlink function closes #54 
2. Moving WRF/WPS paths to config yml is part of #55, though the issue originally suggested moving to resources/ens_vars.yaml. Pros/cons? Start with this PR change and modify later if needed?

**Comment by michelleharrold** [comment]
I was also able to run all the tests successfully (setup, Test 1, Test 2, Test 3, Test 4, Test 5). I double checked the symlink mods are working for staged data and pulling data - success. 

Side note #1: These are handy enhancements!
Side note #2: I had some issues with setting a new case (i.e., not test), but I think that was user error. I will follow-up on Slack to make sure I know the current protocol.

**Review by michelleharrold — APPROVED** [review]

**Comment by mkavulich** [comment]
Changing priority to "blocker" as this PR must be merged before #69.

**Comment by fossell** [comment]
@mkavulich - Did you need anything further on this PR before merging? I will approve, and would be ok with leaving issue #55 for further discussion and enhancement separate from this PR.

**Review by fossell — APPROVED** [review]

**Pull request merged**
