### PR TITLE
46-height-selector

### LINKED ISSUE #46: Height Selector Refinement
How will the vertical level slider bar will integrate with the variables being plotted?
        Obviously 2m TMP and precip are at the surface. If selected, will those always be displayed? Or will they only be displayed when the slider bar is at the bottom?
        Can we assume that users will know the units of the slider bar are millibars? Perhaps the value pop up should say "950mb" instead of just "950"?

## Describe the Enhancement ##
*Provide a description of the enhancement request here.*

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**

### Projects and Milestone ###
- [ ] Select **Project**
- [ ] Select **Milestone** as the next official version or **Backlog of Development Ideas**

## Enhancement Checklist ##
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>/<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project**, and **Development** issue
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

### PR DESCRIPTION
**Pull request by hahnd**
## Expected Differences ##

The purpose of the height/pressure level selector should be more clear to the user.

## Pull Request Testing ##

The code is deployed to the website.  Test it on a variety of devices and browser window sizes.

## Pull Request Checklist ##
- [x] Review the source issue metadata (labels, project, and milestone).
- [x] Complete the PR definition above.
- [x] Ensure the PR title matches the feature or bugfix branch name.
- [x] Define the PR metadata, as permissions allow.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue and delete your feature or bugfix branch from GitHub.

Closes #46

### CODE REVIEW

**Review by fossell — COMMENTED** [review]
The vertical slider labels are a valuable addition, looks good.  Is it possible to default the slider at the lowest level (e.g. 1000mb)? Since temperature is not displayed at upper levels, it's a little confusing to select the 3D temp and have nothing happen. Since there is valid data for all variables at lowest level, might be better off defaulting to that?

**Comment by hahnd** [comment]
Good catch...I had to reverse the order of the array of pressure levels, and left the default value as index 0.  I have updated the code to default to the last index of the array, so that we use the lowest pressure level (1000 mb).  Changes are deployed.

**Comment by fossell** [comment]
@hahnd - Hmm, I'm still seeing the same default behavior. When I select a wrf job, then once the forecast viewer loads I select 3D temp, the vertical selector starts at 100mb with no data displayed. Same behavior for other 3D fields too. I looked at the WI run and the "short test" caribbean run.

**Comment by hahnd** [comment]
Maybe clear your browser cache.  It’s working for me.

**Pull request merged**
