### PR TITLE
Feature/139 job details and delete

### PR DESCRIPTION
**Pull request by hahnd**
## Expected Differences ##

- [ ] Do these changes modify the system output in any way? **[Yes or No]**</br>
No

## Pull Request Testing ##

Describe testing already performed for these changes:</br>

- [x] Open job details
- [x] Check that action buttons are appropriate for the job's state (Cancel, Delete, Open Viewer, Close)
- [x] Launch a job
- [x] Cancel the job
- [x] Check that CloudFormation stack for the cluster was deleted after cancel is finished.
- [x] Delete a job that has completed
- [x] Check that data are removed from S3 and the job is no longer in the list
- [x] Review layout on desktop and mobile devices.

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>
Changes are deployed to app.wrfcloud.com, so you can use that to test.

- [ ] Do these changes include sufficient documentation updates, ensuring that no errors or warnings exist in the build of the documentation? **[Yes or No]**

- [ ] Do these changes include sufficient testing updates? **[Yes or No]**

- [ ] Will this PR result in changes to the test suite? **[Yes or No]**</br>
If **yes**, describe the new output and/or changes to the existing output:</br>

- [ ] Please complete this pull request review by **[Fill in date]**.</br>

## Pull Request Checklist ##
- [ ] Review the source issue metadata (labels, project, and milestone).
- [ ] Complete the PR definition above.
- [ ] Ensure the PR title matches the feature or bugfix branch name.
- [ ] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)**
Select: **Project**
Select: **Milestone** as the version that will include these changes
Select: **Development** to link to the original development issue.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue and delete your feature or bugfix branch from GitHub.

### CODE REVIEW

**Comment by fossell** [comment]
@hahnd - Where on S3 should we see a particular job and ensure it's been deleted (when testing that function on the UI)? I was looking under wrfcloud-output/output for the job ID, but not finding any matches.

**Comment by hahnd** [comment]
Yes, you can look under s3://wrfcloud-afdd9908/output/ to see if it is gone.

**Comment by fossell** [comment]
@hahnd - Thanks, I see it now. I deleted job WFAB89290FF from the UI, but it's still present on s3://wrfcloud-afdd9908/output/. Does it take a while to delete from s3? It's been about 15-20min.

**Comment by hahnd** [comment]
Should be instantaneous.  The way we store the job and output data has changed recently, so try one that is not too old.  Maybe the “Denver Storm!” case I ran a couple of days ago: W3B6A7A0EE1

**Comment by fossell** [comment]
@hahnd - Hmm, I tried to Denver storm now, W3B6A7A0EE1, but it's still on s3.

**Comment by hahnd** [comment]
That code is probably not working then.

**Comment by hahnd** [comment]
@fossell - I just pushed a bug fix to this branch and deployed the API.  Data should be removed when you delete now.

**Comment by fossell** [comment]
@hahnd - It works!

**Review by fossell — APPROVED** [review]
@hahnd - I went through the suggested tests and after your recent mods confirmed a job can be deleted from the UI and s3 bucket. Looks good on web and mobile devices too.

**Pull request merged**
