### PR TITLE
Feature 214 change precip accum colorbar

### LINKED ISSUE #214: Change color bar of precip accum
## Describe the Enhancement ##
Request from Paul: The brown for low precip accumulations is distracting, can the precipitation accumulation colorbar be switched to the precipitable water colorbar? 

### Time Estimate ###
2 hours w/ testing

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
June 30, 2023

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [x] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**

### Projects and Milestone ###
- [x] Select **Project**
- [x] Select **Milestone** as the next official version or **Backlog of Development Ideas**

## Enhancement Checklist ##
- [x] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [x] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>/<Description>`
- [x] Complete the development and test your changes.
- [x] Add/update log messages for easier debugging.
- [ ] Add/update tests.
- [ ] Add/update documentation.
- [x] Push local changes to GitHub.
- [x] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project**, and **Development** issue
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

### PR DESCRIPTION
**Pull request by fossell**
- [x] Do these changes modify the system output in any way? **[Yes ]**</br>
If **yes**, please describe:</br>
These changes will change the color palette used for contouring the precipitation accumulation plot. The changes are just in visual appearance and should not change the underlying data. 

These changes close #214 

## Pull Request Testing ##

- [x] Describe testing already performed for these changes:</br>
No testing has been done. I'm unsure how to deploy and view these changes. 

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>
If possible to deploy these changes to simply view with existing runs, that should be sufficient. Otherwise launch a simple quick run to visually inspect the precip accumulation field to ensure it's using the new color palette.

- [ ] Do these changes include sufficient documentation updates, ensuring that no errors or warnings exist in the build of the documentation? **[No]**
None needed.

- [ ] Do these changes include sufficient testing updates? **[No]**
None needed. 

- [ ] Will this PR result in changes to the test suite? **[No]**</br>
If **yes**, describe the new output and/or changes to the existing output:</br>

- [ ] Please complete this pull request review by **[Friday, June 16]**.</br>

## Pull Request Checklist ##
- [x] Review the source issue metadata (labels, project, and milestone).
- [x] Complete the PR definition above.
- [x] Ensure the PR title matches the feature or bugfix branch name.
- [x] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)**
Select: **Project**
Select: **Milestone** as the version that will include these changes
Select: **Development** to link to the original development issue.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue and delete your feature or bugfix branch from GitHub.

### CODE REVIEW

**Comment by fossell** [comment]
@georgemccabe or @hahnd - Could one of you please review and test? I don't know how to test these changes on the UI. I can take a look at the plot after it's updated to confirm it's what we're looking for, but just not sure how to deploy this. Thanks!

**Comment by georgemccabe** [comment]
@fossell , sure I can test it. I will have to start a cluster and run a job using your branch. Do you have a preference on which job to run? I can rerun an existing job.

**Comment by fossell** [comment]
@georgemccabe - Thanks! I was looking at W981D5734FB as an example, but really any job that has some precip is fine. Note that precip accum will be zero at initialization (fhr 0), so we don't expect anything at time zero, need a couple hours of output to confirm it's working properly.

**Comment by georgemccabe** [comment]
@fossell, OK I am currently running a new job W2714436F78 that uses the same configuration as W981D5734FB but will use your feature branch so we can compare new/old.

I noticed some jobs like [W328106FD2E](https://app.wrfcloud.com/view/W328106FD2E) have all brown values for the 0 hr lead. Do you know why that would be?

**Comment by georgemccabe** [comment]
Job [W2714436F78](https://app.wrfcloud.com/view/W2714436F78) used the changes. It looks like the 0 hr lead is all purple. I confirmed that all of the values are 0.

**Comment by fossell** [comment]
@georgemccabe - Thanks! This looks good. We should probably revisit color scales in the future. It would be nice to have all of the 0 data have no color and only start filling contours above a certain threshold, but that applies to more products and is beyond the scope of this issue. I'm happy with what we have here for now, if there is nothing else please approve and I'll merge. thanks!

**Review by hahnd — APPROVED** [review]

**Pull request merged**
