### PR TITLE
Feature 29/password recovery

### LINKED ISSUE #29: Password Recovery
## Describe the New Feature ##
Allow users to recover their account in the event of a lost password through the web application.

### Acceptance Testing ###
 - User can reset their password through the web application:
     - From the login screen, enter email address, click "Forgot Password", and click "Recover Password" button.
     - Check email with a link to reset your password.
     - Update your password.
     - Logout and Login with new password.

### Time Estimate ###
4h

### Relevant Deadlines ###
None

## New Feature Checklist ##
- [x] Complete the issue definition above, including the **Time Estimate** and **Funding source**.
- [x] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>/<Description>`
- [x] Complete the development and test your changes.
- [x] Add/update log messages for easier debugging.
- [x] Add/update tests.
- [x] Add/update documentation.
- [x] Push local changes to GitHub.
- [x] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [x] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project**, and **Development** issue
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

### PR DESCRIPTION
**Pull request by hahnd**
API changes:
  - Added the RequestPasswordRecoveryToken API action.
  - Granted permission to anonymous users to run the RequestPasswordRecoveryToken action.
  - Updated the email template to reset a password.
  - Added step when validating reset token to check the expiration time.

UI changes:
  - Added section to Login page to show recovery instructions after a token request has been successfully submitted.
  - Added button and code to submit recovery request to API
  - Added ResetPassword component to allow user to reset password with the link from the email.

Tests:
  - Fixed a few tests
  - Added new tests to cover new API code

## Expected Differences ##

- [ ] Do these changes modify the system output in any way? **[Yes or No]**</br>
No

## Pull Request Testing ##

- [ ] Describe testing already performed for these changes:</br>
Ran pylint on the API, ran test suite on the python package, wrote new tests for new Python code and checked coverage, tested UI to reset passwords.

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>
@michelleharrold and @fossell - 
  1. Go to https://www.wrfcloud.com and pretend you forgot your password.  Try to reset your password and report any errors or anything awkward in the UI.  Reset it again with the intent to break something.
  2. Review logic in wrfcloud.api.actions.users.RequestPasswordRecoveryToken and wrfcloud.api.actions.users.ResetPassword classes.  Focusing on the perform_action functions in each class.

- [ ] Do these changes include sufficient documentation updates, ensuring that no errors or warnings exist in the build of the documentation? **[Yes or No]**

- [ ] Do these changes include sufficient testing updates? **[Yes or No]**

- [ ] Will this PR result in changes to the test suite? **[Yes or No]**</br>
If **yes**, describe the new output and/or changes to the existing output:</br>

- [ ] Please complete this pull request review by **[Fill in date]**.</br>

## Pull Request Checklist ##
- [ ] Review the source issue metadata (labels, project, and milestone).
- [ ] Complete the PR definition above.
- [ ] Ensure the PR title matches the feature or bugfix branch name.
- [ ] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)**
Select: **Project**
Select: **Milestone** as the version that will include these changes
Select: **Development** to link to the original development issue.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue and delete your feature or bugfix branch from GitHub.

Closes #29

### CODE REVIEW

**Review by fossell — APPROVED** [review]
I was able to successfully reset password. The UI and reset email were simple and intuitive, I had no issue following the instructions and resetting it. I also tested a few failures like submitting the wrong email, requesting to reset within the 10min time minimum, and entering incorrect passwords. These all failed as expected with clear error messages that pop up. The perform_action functions make sense and everything seems to behave as expected.

**Comment by michelleharrold** [comment]
I was able to successfully reset my password on my first attempt. After that, I tried to throw it some failure points:

1) Wrong password - worked as expected
2) Wrong email - worked as expected
3) Waiting less than 10 minutes for new request - worked as expected
4) I asked to recover my password but then "remembered" my password after getting the new link. I typed my password and successfully logged in. The password reset link in my email brought me to the 'Launch a WRF' job page - not sure what the anticipated behavior should be but wanted to test "remembering" a password after asking to reset it.5) I was doing some testing on Google Chrome, left for >60 minutes, came back and tried to recover my password, and it said I hadn't waited 10 minutes...and now I am in a weird state of not being able to reset my password! Error was: Action FailedYou must wait at least 10 minutes before requesting another reset emailRef ID: 28F6272192

Regarding the UI, it is great! The only feedback - take or leave - when I hover my mouse over the 'I forgot my password!' on the login page or 'I remembered!' button on the recovery page, would it be possible to have the same behavior as the blue buttons when you hover and see the white cartoon hand cursor?

Code all looks good to me! Only one small comment -- I saw there are minimum complexity requirements for the passwords. Should that be posted on UI when making a new password? I can go either way.

**Comment by hahnd** [comment]
@michelleharrold Good catch on number 5!  I found a logic error in `User.get_seconds_since_user_reset_token_sent()`, where I need to calculate the value with `now - then` rather than `then - now`.

Created a unit test so that the original code fails:
```
>       assert 10 > token_age > 0
E       assert -0.027198076248168945 > 0
```
Then fixed the coding error and verified that the test passes.  This error is deployed and should be fixed now.
 
<hr/>

I updated the SASS file to change the mouse pointer, color, and underline when the mouse hovers over the 'I forgot my password!' and 'I remembered!' links.  It's deployed now, so you can see it again.

<hr/>

The password complexity hints should be shown on the screen when changing a password.  Are you unable to see them?  I have attached screen captures here.
Screen Shot 2022-08-09 at 2 51 15 PM
Screen Shot 2022-08-09 at 2 51 39 PM
Screen Shot 2022-08-09 at 2 51 45 PM

**Comment by michelleharrold** [comment]
@hahnd - Ah, I totally missed the password requirements (must have had the window formatted weirdly) - anyway, user error on my part! I think this is in good shape!

**Review by michelleharrold — APPROVED** [review]

**Pull request merged**
