### PR TITLE
Feature/api audit log

### LINKED ISSUE #7: API Audit Logs
## Describe the New Feature ##
The API should log details for each request received.  This will help to locate error logs when users report problems and  track system activity.

### Acceptance Testing ###
The current tests for the API handler can be updated to make sure there is an entry in the *audit log* database table and that values are set appropriately for the test request.

### Time Estimate ###
8h

### Relevant Deadlines ###
NONE

### Assignee ###
- [X] @hahnd

### Labels ###
- [X] API
- [X] High

### Projects and Milestone ###
- [X] wrfcloud
- [X] Version 0.1

## New Feature Checklist ##
- [x] AuditEntry class to store log entry properties
- [x] AuditDao class (Data access object) to handle DynamoDB transactions
- [x] DynamoDB table definition
- [x] Save method to save a log entry to the audit table
- [x] Read method to read a log entry from the audit table based on reference ID
- [x] Unit tests will sufficient code coverage

Branch name: `feature_<Issue Number>/api-audit-log`
- [x] Complete the development and test your changes.
- [x] Add/update log messages for easier debugging.
- [x] Add/update tests.
- [x] Add/update documentation.
- [x] Push local changes to GitHub.
- [x] Submit a pull request to merge into **develop**.

Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project**, and **Development** issue
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

### PR DESCRIPTION
**Pull request by hahnd**
Closes #7 

## Expected Differences ##

- [ ] Do these changes modify the system output in any way? **[Yes or No]**</br>
No, additional functions.

## Pull Request Testing ##

- [ ] Describe testing already performed for these changes:</br>
Run python/coverage.sh -- requires a local dynamodb running for most tests and a 'junk' profile in your AWS credentials file.  This can be automated in the CodeBuild testing later.

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>
Setup for testing could be non-trivial.  All of the tests have passed in my environment.  We should prioritize setting up CodeBuild once we get our AWS account.

- [ ] Do these changes include sufficient documentation updates, ensuring that no errors or warnings exist in the build of the documentation? **[Yes or No]**

- [ ] Do these changes include sufficient testing updates? **[Yes or No]**
Yes

- [ ] Will this PR result in changes to the test suite? **[Yes or No]**</br>
If **yes**, describe the new output and/or changes to the existing output:</br>
Yes.  New unit tests have been added.

- [ ] Please complete this pull request review by **[Fill in date]**.</br>

## Pull Request Checklist ##
- [ ] Review the source issue metadata (labels, project, and milestone).
- [ ] Complete the PR definition above.
- [ ] Ensure the PR title matches the feature or bugfix branch name.
- [ ] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)**
Select: **Project**
Select: **Milestone** as the version that will include these changes
Select: **Development** to link to the original development issue.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue and delete your feature or bugfix branch from GitHub.

### CODE REVIEW

**Review by JohnHalleyGotway — APPROVED** [review]
I approve of these changes.

However, this review is rather superficial. I agree that we should prioritize automating Code Build tests to give us more confidence in proposed changes. I see that 19 files have been added/modified. 

I see some changes in how the user attributes are accessed, the addition of api/audit code, updates to the api/handler.py with references to audit logs. I see a new tests for the exercising the audit API. I don't see any obvious issues with the content of the code or its formatting.

Recommend that we start including brief documentation with code changes. Should the creation/updating of an audit log be mentioned in the chapter on [System Administration](https://wrf-cloud.readthedocs.io/en/latest/Users_Guide/administration.html)?

**Comment by hahnd** [comment]
Good idea on the documentation.  I have added a section and committed here.  Will request another review.

**Comment by JohnHalleyGotway** [comment]
@hahnd I went to review your updates to the documentation but don't see any changes to the "docs" directory included in this PR. Did you make those changes on some other branch or are you still working on it?

**Comment by JohnHalleyGotway** [comment]
@hahnd I went to review your updates to the documentation but don't see any changes to the "docs" directory included in this PR. Did you make those changes on some other branch or are you still working on it?

**Comment by hahnd** [comment]
I renamed by branch locally to feature/7-api-audit-log once I had created the issue and got the number.  Seems like this did not change the remote branch name and looks like it became a branch off of that feature branch.  I'll see if I can update this PR to merge the new branch instead.

https://github.com/NCAR/wrfcloud/blob/feature/7-api-audit-log/docs/Users_Guide/administration.rst

**Comment by hahnd** [comment]
Could not change the source branch.  I'll close this one without merging and create a new PR.

**Pull request closed without merging**
